### ISSUE TITLE
Event text is truncated even though there's plenty of space on the screen.

### ISSUE THREAD

**Issue by caseymarcallen** [datalust/seq-releases#249]
The event view seems to have an arbitrary truncation of event text even though there's plenty of space available on the screen. This means I have to select each event to open it and see what the actual event was even though it should all just display right on the event view.

See sample image:

![image](https://cloud.githubusercontent.com/assets/951165/5677026/24664a5a-981b-11e4-8f49-2f0fbea65398.png)

**Comment by nblumhardt** [comment]
LOL "So much unused space over here" :-) ...yes, definitely!

Sorry it's taken a while to get back to you on this one; the problem here is that embedded object data is truncated _within_ the message, and because a single message may include many object properties, it's non-trivial to calculate the right truncation point to maximise space usage.

I think some kind of heuristic ("try to guess 60% of the width for each embedded object) would improve things, will have to leave it aside for the time being but will keep it in mind.

**Comment by caseymarcallen** [comment]
Could you perhaps have a setting that can be enabled to customise the display such that if I have a large, high-res screen, then I can completely disabled the object truncation from within the message and let the Seq UI use its existing `text-overlow: ellipsis` css to do the truncation? 

That way I could make full use of screen real-estate and log messages would rarely be truncated at all, but if I had a smaller screen and was always just cutting the end of my messages off, then the existing behaviour could be enabled so you can try and be smart about showing as much context in limited space as you can.

**Comment by nblumhardt** [comment]
Something along those lines sounds good, thanks for the feedback.

**Comment by nblumhardt** [comment]
Hey Casey - I made some tweaks in v2 to hopefully improve on this, though there will still be some whitespace if depending on how the log message is formatted. It'd be good to know if this is still on your radar - ? Cheers!

**Comment by caseymarcallen** [comment]
Yeah, it has improved *some* log entries but not others.

Those that appear to be a bit better are the ones where the log line may be quite long but its made up of lots of short items concatenated together.

The ones that are still a bit useless are ones where there is a single item in the template that is quite long, like a URL for example. 

Unfortunately its the URL ones that are particularly frustrating because usually the important differentiating parts of the URLs are at the end and are being cut off.

With a 27" 2560 x 1440 monitor, there is still a whooooole lot of empty white space on the screen.

I don't think this can be properly solved (at least in my use cases) unless there is the ability to simply turn the object truncation off altogether.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. I'll check out what it would take to disable it on a per-user basis. Cheers!

**Comment by nblumhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/342712/19917518/af599366-a10f-11e6-982d-59ea43e09a61.png)

The effective limit (to prevent crazy browser drawing issues) is now 1024 characters. I know it's not _limitless_ but unless you're out buying a Surface Studio it should be okay for now ;-)

(JSON values will still be truncated as before - they're otherwise pretty hideous to behold. If there's feedback that we need to change the default there I'll circle back.)

Thanks again!

**Comment by caseymarcallen** [comment]
:clap: Awesome... love your work. I'll check it out when it gets released.
