### ISSUE TITLE
Generate automatic name for signals created from simple filters

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-releases#295]
When creating a signal from a filter, it would be nice if the signal had a name more explicit than "New signal" .
At least, for simple filters like `PropName == PropValue` , the signal could be created with name `PropName:PropValue`.
(that would also help classifying in the collection of signals)

**Comment by nblumhardt** [comment]
Thanks for this suggestion! I have given it some more thought (I've had a year ;-) ) and decided that, while there are definitely cases where doing this would save some keystrokes, it's unlikely Seq can implement this in a way that will feel consistent and predicatable, and generate mostly-useful titles.

Since signals are such a fundamental part of the UI, hopefully the manually-created signal names will be  more useful over the long-run.

Cheers!
