### ISSUE TITLE
Installing vNext of existing app, doesn't update existing app

### ISSUE THREAD

**Issue by caioproiete** [datalust/seq-releases#355]
Is this the expected behavior?

![image](https://cloud.githubusercontent.com/assets/177608/11288651/6e609fc4-8efc-11e5-91ae-8dc478c019c7.png)

**Comment by nblumhardt** [comment]
Thanks for the note. To update an app the "Manage..." link will do this; I am not sure that supporting multiple versions the way we do now is great, but I'm also not sure disallowing it makes sense either. I'm inclined to close this as it stands - what do you think?

**Comment by andymac4182** [comment]
Maybe an `Update` button next to `Manage...` when there is an update available for that application will encourage people to update instead of installing multiple versions accidentally and when installing a new version of an existing app ask if they meant to update that application. This would allow the existing behaviour to still work while helping to guide users to the outcome they are looking for.

**Comment by nblumhardt** [comment]
In 3.4, there is now a "Check for package updates" setting and an "Update" button that will be displayed when app updates are available.

![image](https://cloud.githubusercontent.com/assets/342712/20167696/dc064e0e-a768-11e6-89e8-b06e291d927d.png)
