### ISSUE TITLE
Relative timestamp predicates in queries (@Timestamp > Now() - 3d, etc.)

### ISSUE THREAD

**Issue by AntoineGa** [datalust/seq-releases#361]
I would like to add a Signal which filter events on the last X Days / Hours.
In order to do this, i would need a function giving me the current timestamp, eventually substracted of X Days / Hours to compare with @Timestamp events.

As i have not find this in the documentation, i suggest this functionnality.

**Comment by nblumhardt** [comment]
Thanks for the suggestion Antoine!

How would this differ from `DateTimeOffset.UtcNow` on the server?

Regards,
Nick

**Comment by AntoineGa** [comment]
Hi,

If we have the opportunity to add a shift and construct a datetime (which is already possible as per documentation), that would do the trick !

I realize now that could be achieved from query (relying on Js / whatever language has constructed the query) to compute the UtcNow.
The issue is only related to filter on  a value relative to user using Seq UI and Signal.

**Comment by nblumhardt** [comment]
Thanks for the follow-up, this makes sense. I didn't realise you were referring to the query language - `Now()` would be a handy function :+1:

**Comment by AntoineGa** [comment]
Seq and Serilog are awesome !

**Comment by nblumhardt** [comment]
Another relevant thread: http://docs.getseq.net/v3/discuss/579955fea7f817170056f5ef

This kind of feature should support predicates like:

```sql
@Timestamp > Now() - 3d
```

A couple of considerations:

 * For simple predicates, there shouldn't be a performance difference between specifying the time range in the query and using the explicit range selector
 * To make good use of the query cache (and so that results evolve "consistently" as time passes) it seems like it would be judicious when computing timeseries to align the "from" end of the range to e.g. minute boundaries (or whatever is appropriate for the interval); this will have the effect of showing the most recent slice as incomplete though, so some opt-out that's to-the-millisecond would be required, too. Perhaps `Now()` could be integral when used in this fashion, and another function like `Instant()` give a precise time?

**Comment by nblumhardt** [comment]
Just a quick update on this; it's rather a lot larger than it appears, but the work is necessary to meet the longer-term goal of a comprehensive (text) query interface to Seq, so I've been pushing forwards with it for a few days. Expecting to have some progress to show soon!

**Comment by nblumhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/342712/22768676/682918aa-eecf-11e6-9402-eea9fa3d87ff.png)

Nearly done; basic time expressions like the one above are now translated into index bounds when possible (e.g. when alone or joined with other expressions with `and`).

Still to go:

 * More optimization
 * UI tweaks to make time range constraints and the "from"/"to" date selectors work nicely together when executing SQL queries

@centur this should be getting close to what you need for bookmarkable "recent events" queries. Keen to know if you can spot any flaws/omissions for your use case.

Cheers!

**Comment by centur** [comment]
Looks great, and seems like covers what we need, especially if it will be reflected in URL and we can bookmark it :).

Have just one question - does this act as a sliding window, e.g. having `@Timestam > Now() - 15m` means that it will always show the last 15 mins of the logs rather than "everything since FirstRefreshTime-15mins" ? in second case display would grow over time... 

Not very fast about it as in our dashboard we are refreshing pages anyway so it will be refreshed by an extension. But being clear about the type of constraint can proactively answer some questions :)

**Comment by nblumhardt** [comment]
Great to hear.

The logic is executed when the query is run, so it'll be a sliding window - which sounds like what you need 👍

**Comment by nblumhardt** [comment]
SQL queries will now default the date range "from" box to -24h, but when the value is cleared the query can be run over any arbitrary date range.

![image](https://cloud.githubusercontent.com/assets/342712/22773150/522610d6-eeec-11e6-9033-ad81d41ae18f.png)

Although this seems like it would thwart the "bookmark" use case, an arbitrarily early "from" date could be supplied (e.g. _2015-01-01_) so that the more restrictive one in the query will take precedence.

One (relatively easy) thing to go - `@Timestamp > DateTime('2017-01-01')` constant comparisons should also use the index. Knocking that one over then ready to merge and cut a new pre-release build.
