### ISSUE TITLE
Unhandled exception during service stop attempt : The extent is temporarily offline

### ISSUE THREAD

**Issue by ylashin** [datalust/seq-releases#408]
SEQ issue in v 2.2.8 & 2.4.2
SEQ is hanging meaning the browser console is not opening the home page. When trying to restart the windows service it does not stop and the below is logged in event viewer :

```
Failed to stop service. Autofac.Core.DependencyResolutionException: An exception was thrown while executing a resolve operation. See the InnerException for details. ---> The extent 4/13/2016 is temporarily offline (See inner exception for details.) ---> Seq.SeqException: The extent 4/13/2016 is temporarily offline
   at Seq.Storage.Events.Extents.Extent.BeginSession(String tag)
   at Seq.Storage.Events.EventStore.<GetFromExtent>d__11.MoveNext()
   at Seq.Storage.Events.EventStore.<Get>d__10.MoveNext()
   at System.Linq.Enumerable.<TakeIterator>d__24`1.MoveNext()
   at Seq.Storage.Events.EventStore..ctor(String extentsPath, WorkerPool workerPool, MemoryThresholds memoryThresholds, BroadcastChannel broadcast)
   at Seq.Server.SeqServerModule.InitStorageSubsystem(IComponentContext c)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass1`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)...
```

**Comment by nblumhardt** [comment]
Hi Yousry, thanks for getting in touch.

Have you killed the Seq.exe service with Task Manager and tried to restart?

Also, can you please let me know which OS version you're running?

Many thanks!
Nick

**Comment by ylashin** [comment]
Hi Nick

I had the problem on 2 machines:
1 - My local dev laptop Windows 10 Pro 64 bit SEQ version 2.4.2
2 - Azure VM Windows Server 2012 R2 64 bit SEQ version 2.2.8

On Azure VM I did disk check plus a restart which resolved the problem
On my laptop, I tried to restart SEQ service from services console. I do not want to kill it for now as an evidence that it is stuck to be an entry point for troubleshooting. I can try the restart and see if this resolves it or it is disk check or something else

Thanks

**Comment by nblumhardt** [comment]
Thanks for the follow-up Yousry! Surprised to see this occur in two different installs - is there anything common between them (installed apps perhaps?) that would make these two out of the ordinary?

If you are able to send the log files from `C:\ProgramData\Seq\Logs` for either of them to support@getseq.net there may be some clues for me there. Killing/restarting the process is probably fine at this point, I'd say we're seeing the symptom of an earlier hiccup rather than something we can actively dig into in the live process :+1:

**Comment by ylashin** [comment]
Logs sent

Restarting the machine does not fix the issue, killing the process and starting it again fixed it on dev laptop.

**Comment by nblumhardt** [comment]
Thanks, checking out the logs now. Just so I am sure I'm on the same page:

 * Both machines are back up
 * The Azure machine required a disk check
 * A process restart was sufficient on the dev laptop

Correct?

**Comment by ylashin** [comment]
- Both machines are up
- Azure machine required a disk check but I made it just as a shoot in the dark and did also a restart and it worked.
- On dev laptop I killed the process using task manager. Stopping it using services console did not work. Then starting it from services console and it was back again

**Comment by nblumhardt** [comment]
Excellent, thanks for confirming. Will let you know what I find!

**Comment by nblumhardt** [comment]
Hi Yousry,

It looks like this is a variation on https://github.com/continuousit/seq-releases/issues/325, which you've been unlucky and encountered twice out of chance.

Both times the issue occurred immediately after a restart; sometimes, when I/O is particularly slow either because it is limited (Azure) or during some system event (dev laptop?), initialization of the storage subsystem can take longer than the 5sec. timeout that's allowed.

Normally this is fine, but during startup it can put a spanner in the works. The fix in the issue linked above deals with this partially, but it appears the "apps" subsytem is not covered and will need to accommodate this as well.

In both cases a restart of the Seq process should have been sufficient to sort things out, but it looks like the first attempt to restart may have encountered the timeout as well.

Hopefully you won't see this again, but a fix will be coming in the next Seq build anyway.

Thanks for the report and detailed follow-up!
Nick

**Comment by nblumhardt** [comment]
Think I have this sorted out - tentative fix will be in the next prerelease build.
