### ISSUE TITLE
HAVING in SQL queries

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#416]
e.g.

```sql
select count(*) as c from stream group by MachineName having c > 10
```

**Comment by tsimbalar** [comment]
expecting this would also work on fields that are not part of the select, or using a "non-aliased" version 
- `select MachineName, mean(SomeProperty) from stream group by MachineName having count(*) > 0`
- `select MachineName, mean(SomeProperty) from stream group by MachineName having mean(SomeProperty) > 10`

Just to add the "*So that ...*" in the "*As a user, I want a HAVING statement So that ...*"  ... The goal is to quickly detect patterns in the stream of events : 
- `select count(*) as c from stream group by time(1h) having c > {some baseline}` : burst of errors at a given time
- `select percentile(ResponseTime, 95) as c from stream group by time(1h) having c > {a SLA}` : detect period where we do not respect some agreed upon SLA

**Comment by nblumhardt** [comment]
Thanks for the examples. Using expressions not present in the column list is possible but might be a "stretch goal" depending on how the implementation comes out :+1:

**Comment by nblumhardt** [comment]
Basic (alias-driven) version done; requires some reworking of `LIMIT`, which needs to be applied after, rather than before, evaluation of the `HAVING` predicate. The `LIMIT` work is also a TODO for timeseries queries and will be necessary for full `ORDER BY` support, so moving forward with all of that.

**Comment by nblumhardt** [comment]
`LIMIT` reworked, and some perf improvements squeezed out of the new version.

![image](https://cloud.githubusercontent.com/assets/342712/15063420/88a9dd30-138d-11e6-9877-4b913f02588c.png)

One glitch remaining - time slicing still returns all slices, so it'd be tricky to find, say, all SLA violations over a year:

![image](https://cloud.githubusercontent.com/assets/342712/15063392/3b76dd4c-138d-11e6-9da9-f2a4fde01ab6.png)

...so that's next up, then a preview release.

**Comment by nblumhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/342712/15063699/68fda69a-138f-11e6-97c5-54a2fa8c2b22.png)

Done. Adding a separate ticket for non-time `ORDER BY`.

**Comment by tsimbalar** [comment]
Excellent :)
