### ISSUE TITLE
Feature Request : better readability for Message Type filters

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-releases#500]
Filtering the message stream based on _Message Type_ (using quick filters) is one of the most common actions we do when looking for some specific events, and it's great for one-off/throwaway filters. 

But because those filters include filtering conditions based on a "hash", once we start storing them as signals/saved queries and go back to them later, **figuring out what was the actual filter is pretty hard for a regular human being** :)
It is also hard in scenarios where you know you can _sometimes_ get messages with the template `This is the template for a very uncommon and yet super duper important message with {CriticalInformation}` , and need to **set up a filter / signal / Alert (email or similar) before the event has ever been generated** (and therefore you don't have any sample message and don't know the hash value).

It would be nice if we could keep the information about the actual _Message Template_ that we are filtering on.

I can see several options of doing it, (and there are certainly more ! :p) :
- include **comments** in the filter (I don't know if the filter syntax -sql or other- supports comments) that contain the "human version" of the Message Template ... (that wouldn't really help on the 2nd scenario)
- have the query engine support **human-readable queries** `@MessageType == "My Message Template with {CurlyBrackets}"` / `@MessageType = 'My Message Template with {CurlyBrackets}'` filters instead of a a hash (but under the hood, **use the hash when actually executing the query**)
- some other way I haven't thought of ...

I believe this would also help when generating links to pre-filtered event stream from external applications. 

**Does that seem to make sense ?** 

_I don't have access to my Seq instance right now, so I may have confused variable names `@MessageType` and `@MessageTemplate`._

**Comment by nblumhardt** [comment]
Thanks for the suggestion @tsimbalar. I think this one is the way to go (though the variable's called `@MessageTemplate`):

> have the query engine support human-readable queries @MessageType == "My Message Template with {CurlyBrackets}" / @MessageType = 'My Message Template with {CurlyBrackets}' filters instead of a a hash (but under the hood, use the hash when actually executing the query)

Will have a shot at squeezing this in :-)

**Comment by tsimbalar** [comment]
right, `@MessageTemplate` vs `EventType`, minor brain fart here :)

So yes, having equality filters on `@MessageTemplate` perform as well as filters on `@EventType`. 

Ideally using quick filters (include/exclude based on event type) would also generate that kind of human-friendly filter ... but I do understand that using those hashes in the filter expression makes it clearer that it is more efficient.

Another option might be to have a way of saying : 
```
@EventType = HashFromTemplate("this is my full template with {OneProperty} and {AnotherProperty} in here")
``` 
and similar in SQL-ish syntax.
(hopefully with a better name than `HashFromTemplate`)

**Comment by nblumhardt** [comment]
_Type_ > _Exclude_ will already generate that kind of filter today:

![image](https://cloud.githubusercontent.com/assets/342712/19747742/d9270258-9c20-11e6-83f2-7cc7c29173d5.png)

Unfortunately, when the quick filter is to include an event type, it goes via the filter bar, where the "description" field used in the example above can't be represented.

I would like to explore the `@MessageTemplate` filtering mentioned above, but we could get quite far by just keeping a mapping of type -> message template behind the scenes when _Type_ > _Find_ is selected, so that `>>` to the signal bar can look up the description on-the-fly in these cases......

**Comment by nblumhardt** [comment]
Okay, after giving it some more thought, I've settled on your suggestion:

![image](https://cloud.githubusercontent.com/assets/342712/21212077/f4cad68a-c2d4-11e6-87c9-b1171cfa502b.png)

This is generated from a new menu item under _Type_ called _Find from template_.

I took this route after realising that anything based on `@MessageTemplate` would be wrong in the case of events that don't have an `@EventType` that corresponds exactly with their `@MessageTemplate`. This situation arises when an explicit event type is sent along with the event, which the current SLAB, NLog and log4net clients all take advantage of.

`ToEventType()` can be optimised by pre-computing the hash (which in turn is used for faster filtering from disk if necessary), but still makes it clear that a value is being computed dynamically, so it won't be as surprising if the value returned from `ToEventType()` isn't the same one that is attached to the event.

Hope this makes sense, and thanks again for all the input!

**Comment by tsimbalar** [comment]
Oh, I didn't know `@MessageTemplate` and `@EventType` could be set independently. I believe that possibility is not exposed in Serology, is it ?

**Comment by nblumhardt** [comment]
> not exposed in Serology, is it ?

Got to love autocomplete :-)

No, it's not exposed in Serilog - this is mostly because Serilog doesn't have a first-class concept of event types, they're always derived from the template.

(I did look at using this in Seq to provide first-class support for _Microsoft.Extensions.Logging_'s `EventId`, but because this is scoped to the log source it's not a great fit. It also doesn't seem to be used much/consistently in the _MEL_ logs I've inspected, so I feel like Serilog's implicit approach is a pretty good one.)

**Comment by tsimbalar** [comment]
"Serology", that would be a pretty great lib name :) . I should hurry and register the name :)
