### ISSUE TITLE
User/View filter is erroneously populated by Firefox auto-complete; needs explicit opt-out

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-releases#533]
Hi,

I see a strange behaviour when administrating the users that connect to our Seq instance, (settings > users > click on a user) the field "View Filter" is populated with my e-mail address

![image](https://cloud.githubusercontent.com/assets/160544/22499309/40178e04-e85e-11e6-86a1-865abc41e1f1.png)

That is a bit disturbing and unexpected :), and if I save the user information without paying too much attention, I would probably mess up the user profile (saving an absurd default filter).

Note that when seeing the details of **my** user, such a field does not exist!

*As of Seq v3.4.18*

**Comment by tsimbalar** [comment]
Now I'm starting to wonder if it's not because of Firefox remembering my credentials for Seq ....

I have a similar strange behaviour when adding a new AppInstance for EmailPlus : SMTP UserName AND password a pre-populated : 

![image](https://cloud.githubusercontent.com/assets/160544/22502907/62a767bc-e86f-11e6-8087-2ddbd17b0be0.png)

**Comment by nblumhardt** [comment]
Ah, I see - auto-fill strikes again! Yes, it'll be Firefox getting over-eager to help. It's pretty surprising that an input labeled "View filter" would be considered an appropriate place to drop in an email address... :-)

Thanks for spotting these, `autocomplete="off"` should cover it.

**Comment by nblumhardt** [comment]
@tsimbalar I've added `autocomplete=off` to more inputs, but unfortunately the view filter one already has it; it looks like this is a minefield with Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=956906.

There are some "hacks" suggested like adding invisible fields, but since the password field that's there (hidden by the "change password" checkbox) that doesn't seem like it will work.

Instead, I've made the password changer dynamically add/remove nodes to the DOM rather than just show/hide them. This should fix things at least until the checkbox is ticked.

**Comment by tsimbalar** [comment]
I'm having a similar issue as of Seq v4.0.60 on the "Configure App" page for EmailPlus : username and password are populated with information from my password manager U_U.

![image](https://cloud.githubusercontent.com/assets/160544/26572334/d88606d0-4519-11e7-8f60-1dbcde644614.png)


I don't know if to open a new issue or reopen this one ?

**Comment by tsimbalar** [comment]
and just now, I notice that I had reported this one already ... so not sure the issue is actually fixed ..

**Comment by nblumhardt** [comment]
Thanks for the (re-)report, I'll check it out 👍
