### ISSUE TITLE
Expand event when filtering on Id

### ISSUE THREAD

**Issue by tbolon** [datalust/seq-releases#539]
When we filter the event stream on a specific Id, by default seq displays the event collapsed, requiring 1 click to open the details.

It is often useful to share a link to a specific event (on notifications for example) and because there is no real "detail" view for 1 event, the events view could handle the case when there is only 1 event in the results, then by default expand it to display all properties.

**Comment by nblumhardt** [comment]
Thanks for the note Thomas.

If you use the "Pin" menu ("Retain" in Seq 4) and choose "Make permalink", the link will have a `&show=expanded` parameter that will have this effect, as well as prevent the event from being deleted by retention processing.

Does that work for your scenario?

**Comment by tbolon** [comment]
Yes, I will update our email template to include the "show expanded" parameter. That will work for now. 

Perhaps this behavior could be enabled by default on the ui ? I do not really see a use case where the user really wants to see the event collapsed when there is only one event, and I _suppose_ it is not really hard to implement.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. The major consideration when enabling it on the UI is that because results are retrieved in pages, the UI won't know whether the result of a query is just a single event until the loading operation has completed.

This means either the event would expand prematurely, or else we'd have to delay the expansion. Both seem like they would feel a bit unexpected.

I'll tinker with this nonetheless and see how it goes.

**Comment by tbolon** [comment]
Yes, I understand. You can close this issue for now, your workaround works perfectly. Thanks.
