### ISSUE TITLE
Export to CSV file contains no data when a date range is not provided

### ISSUE THREAD

**Issue by BlairPaine** [datalust/seq-releases#572]
We've recently upgraded to version 4.0.60 from 3.3.23 and have noticed an issue exporting events to CSV.

If we apply a filter but don't specify a date range, a CSV file is created but it contains no data. This is the case even when you can see events on screen. If we add a date range then the CSV is correctly populated with data.

Please let me know if you require any other details.

Cheers,
Blair.

**Comment by nblumhardt** [comment]
Thanks for the report, this sounds like a bug, I'll check it out.

**Comment by nblumhardt** [comment]
Hi Blair; digging in further, this one's actually by design - the export returns results for the last 24 hours, rather than "all time" as it did in v3 (a nasty surprise if you weren't expecting to download the entire event store :-)).

Unfortunately it's not obvious what's happening, in the case that there are no matching events in the default range.

I think either forcing selection of a date range, or automatically setting the "from" date selector to -24h, would be better here. I'll try out those options and see what feels more natural.

**Comment by nblumhardt** [comment]
Took a simpler route; when no range is selected the message will be:

![image](https://cloud.githubusercontent.com/assets/342712/26705569/3ded2172-477a-11e7-95c7-30085c1d9e3f.png)
