### ISSUE TITLE
Encode single quotes in permalink URLs

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#596]
Although URLs can validly contain single quote characters `'`, some applications have trouble with pasted URLs containing them.

Seq should always encode `'` when it appears in URLs, e.g. in permalinks and filters.

**Comment by nblumhardt** [comment]
Unfortunately, this turns out to be a bit of a minefield. We can escape apostrophes when generating a URL as a link, i.e. for permalinks, but otherwise this is in the domain of the browser's location API, and varies across browsers and versions.

We'll make the change to permalinks, but might not risk breakage by fiddling with URL generation otherwise.

**Comment by laurencee** [comment]
@nblumhardt I had a think about this one, most of the time for everywhere I have worked with Seq the single quotes really only come into play when people click the tick/cross on the context properties. 

Maybe just changing those tick/cross buttons to generate the filter as double quotes instead of single quotes would make this issue less common when trying to send people links to Seq?

**Comment by nblumhardt** [comment]
Hi Laurence - thanks for the thoughts. Double-quotes aren't valid in Seq's SQL dialect, so generating filters with them can be inconvenient (it's nice to be able to just paste a `select ... where ...` in front of a filter). Probably precludes this option. Cheers!
