### ISSUE TITLE
Dashboard chart timeouts and refresh issues

### ISSUE THREAD

**Issue by BlairPaine** [datalust/seq-releases#597]
Hi,

I have created a dashboard and a number of the charts timeout (typically on first refresh or with a long time range).

![image](https://user-images.githubusercontent.com/13684079/27950778-7e91a324-62fa-11e7-9b3c-947839acc39f.png)

In addition, if I select a short time period, and then change it to a longer period, some charts do not refresh for quite some time. There is also no indication that a particular chat is in the process of updating. A user may not realise this and assume the data is the same as the previous time period.

Adding a [throbber ](https://en.wikipedia.org/wiki/Throbber)and allowing the maximum query timeout to be changed would be helpful.

The queries taking longer than 1 minute are quite simple (i.e. a count of a certain message type).  How can I investigate and diagnose why it's taking so long?

Cheers,
Blair.

**Comment by nblumhardt** [comment]
Hi Blair, thanks for the note.

Just for some context, how long is a "long" time period? A few improvements have been made in 4.1 that should turn around chart refreshes faster, but some charts are always going to take a while to initially populate. If you can send through the _Settings_ > _Diagnostics_ info and recent files from C:\ProgramData\Seq\Logs to support@, I can take a look and see where the bottleneck might be.

The timeout is configurable in user preferences (_your username_ > _preferences_ > _query timeout_).

I just realized that while we do show a spinner when charts are initially loading, we should do the same when the range or interval is changed, instead of the background update done between refreshes. I'll take a look at this before we finalize 4.1 👍

**Comment by vlm---** [comment]
Query timeout set in preferences is probably only for running queries in events tab, dashboards still have 1:00 min limit regardless of any value set in user preferences. At least that's how our installation of 4.0.60 behaves.

**Comment by nblumhardt** [comment]
@vlm--- thanks; changing this in 4.1 👍

**Comment by nblumhardt** [comment]
Spinner will now activate on any change to the range parameters (duration/interval) in 4.1.

@BlairPaine this ticket has a few different facets; I think it'd be most effective to work through a support ticket to see where there might be bottlenecks, and raise new issues if needed. Sound like a plan?

Cheers,
Nick

**Comment by BlairPaine** [comment]
@nblumhardt many thanks and yes that sounds fine. Do you need me to raise a support ticket somewhere?

**Comment by nblumhardt** [comment]
Thanks @BlairPaine - if you can send info to support@getseq.net I'll pick it up there.
