### ISSUE TITLE
Streamlined/quick property-value filtering

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#604]
Signals are often used to select between sets of logs, for example, environments _Dev_, _Test_ and _Prod_, between different applications, or machine roles.

This generally leads to the pattern of having signals such as _Environment - Test_ or _Role - Web Server_.

Since most of these scenarios revolve around the value of a single property:

 1. it'd be nice to just set up an overall selector for that property, and
 2. since the property can have at most one value, have multi-selection use `or` semantics rather than `and` (which never yields results).

An initial straw-man proposal might be to work this into the right-hand bar as a new set of entries similar to the current Signal List, but as a new entry type:

 * When clicking the entry, it would expand to show a list of possible property values, and filtering would not occur until individual values were selected
 * Editing the entry would allow the property name and available values to be chosen

**Comment by tsimbalar** [comment]
That would actually cover this closed issue as well : #295  \o/

**Comment by KodrAus** [comment]
We've been a little quiet here for the last few weeks, but have an update on this feature, which we're calling _signal groups_. These will work their way into [the next preview release](https://getseq.net/Download/Begin?version=4.2.244-pre) and any feedback would be appreciated!

# Signal groups

Signal groups are a feature that's designed to tackle two problems:

- Having precious screen realestate taken up by lots of signals
- Selecting multiple signals with filters that don't make sense being intersected, like `@Level = 'Info` and `@Level = 'Error'`. Essentially any signal that's a simple property equality check will never return any results if we intersect them. It makes more sense to union them, so you'll get `@Level = 'Info' or @Level = 'Error'` instead of `@Level = 'Info' and @Level = 'Error'`

We now automatically group simple equality signals and will union them instead of intersect when multiple signals in the same group are selected. Groups can be collapsed to save space.

This all sounds a bit esoteric so I've included some sreenshots that should give you a clearer picture of what it's all about.

## Expanding and collapsing signal groups

![expand-collapse-signal-groups](https://user-images.githubusercontent.com/6721458/33589598-42892784-d9c5-11e7-8b2e-52b1bc4417d1.gif)

Signals are grouped by the property they're comparing, and can be tapped to expand or collapse. Activated signals in a group will always be visible.

## Creating signals that get grouped

![create-group](https://user-images.githubusercontent.com/6721458/33589958-ca4513b6-d9c7-11e7-943e-22b7d161e184.gif)

Signals with a single equality filter will be grouped and unioned.

**Comment by nblumhardt** [comment]
A few other things you can try in 4.2.244-pre ...

 * If multiple signals are selected in a group, and you use the "add to dashboard" feature to create a chart, the chart will be based on the unioned signals as well
 * App instances and retention policies can be configured using grouped signals (just add them and the grouping will happen automatically)

**Comment by tsimbalar** [comment]
This looks great ! but I'm having issues running Seq v4.2.244.pre ... I'll open a separate issue ...

**Comment by KodrAus** [comment]
Thanks @tsimbalar :+1:

**Comment by tsimbalar** [comment]
I've started playing with it and that's *pretty nice* ! 👏 

I know it's still not finished, but a few comments : 
- I like that it works seemlessly with all the signals I already had :) 
- while it's already quite usable "as is" as a *consumer* (i.e. toggling filters on/off to reduce the number of events in the list), the editing side still feels a bit awkward, and having to : 1. create a signal , 2. give it a name, 3. save ... in order to have it appear in the group is a bit tiring :) 
- I would expect that clicking the header of a *Signal group* would toggle its "children" signals on and off  (and maybe have a collapse/uncollapse symbol for the group on the left rather than on the right ?)
- I think it would be helpful if a few signals were already created out of the box. I think it's safe to say that signals based on `@Level` would be useful for everyone, and would showcase the feature to new comers.

Here are some improvements I would like to see happen :) :
- simplify the creation of simple `Prop == Value` *sub-signals* from an existing signal group. Ideally, I would be able to open some kind of context menu on the signal group, see all the *known* values for that property, and easily add those values as signals under the signal group.
- simplify the creation of simple `Prop == Value` signals from the events list (under the little green check symbol next to properties) without going through the formality of naming the signal manually. For instance an option "Create a signal" from there

![image](https://user-images.githubusercontent.com/160544/33607802-9c3d7a80-d9c2-11e7-97cb-49ad12e6c274.png)

Thanks, and keep up the good work 😎

**Comment by nblumhardt** [comment]
New preview `4.2.280-pre` is on https://getseq.net/Download - fixes the installer and improves a few more things...

![image](https://user-images.githubusercontent.com/342712/33700867-7dacf8a6-db67-11e7-8950-9a03f866484f.png)

**Comment by tsimbalar** [comment]
Looking pretty good :) 😍 

On an upgrade, I didn't get the "Errors" / "Warnings" signals with the pretty colors that I had on a "clean install" ... I could figure out where the colour was stored but noticed that renaming it properly, I could get what I wanted :p ...  I don't know if that's the expected behavior, or some signals that are not explicitly recreated during an upgrade ... just thought I would mention it

To initialize the list of signal faster and get started, I would love something along the lines of
- from the event list, click on the green check mark next to a property name
- click "Create signals for known values"
- and TADA !, a signal is added in my signal list for every known value of that property, hence populating my signal bar
There's probably a risk of accidentally generating a huge number of signals, so some guards might be needed there ("are you sure you want to create 3 gazillions signals?), or a confirmation... Even better would be to show all possible values and possibly select from the available ones (garaying out the ones that already created as a signal) . Christmas is coming, so I'll try putting it on my list to Santa 🎅  ;) ...

**Comment by nblumhardt** [comment]
Thanks for the notes, we'll give this some thought 👍

**Comment by nblumhardt** [comment]
We're going to close this overall ticket as "done" now, as we think the major functional pieces are in place in 4.2.280-pre - we'll raise new issues for further changes.
