### ISSUE TITLE
Line breakes not working for expanded rendered message

### ISSUE THREAD

**Issue by elv1s42** [datalust/seq-releases#620]
Hi!

I'm using Seq 4.1.17 with Seq.Client.Log4Net 2.3.24 and log4net 2.0.8, and I've noticed that logging doesn't look correct for expanded messages.

Here is how the exception message looks like:
![image](https://user-images.githubusercontent.com/6689884/31536626-03f1f168-b008-11e7-99e5-db065cb02186.png)

Here is the same message in Notepad++:
![image](https://user-images.githubusercontent.com/6689884/31536686-33abf9da-b008-11e7-97e5-2b85f2a44181.png)

As you can see, line breaks are not working, and I fixed that by editing seq .css file like this:
![image](https://user-images.githubusercontent.com/6689884/31536758-6e539c46-b008-11e7-8a42-a6485228fbea.png)

After that the message looks like this:
![image](https://user-images.githubusercontent.com/6689884/31536780-85c46d7e-b008-11e7-9a71-47127c2d8b0b.png)

Can you please tell if this fix makes sence and is possible to include it in the next release?

Thank you.

**Comment by nblumhardt** [comment]
Hi @elv1s42 - thanks for the report. Which browser are you using? The menu links don't look quite right in your screenshot either (they're below the exception message, when they should be just under the log message:

![image](https://user-images.githubusercontent.com/342712/31592467-d2cf8ada-b26b-11e7-8c3f-67ad625dd58b.png)

If the browser is modern, can you think of anything else that might cause the menu positioning to change? (Custom browser extension scripts, etc.)

**Comment by andymac4182** [comment]
@nblumhardt From memory the log4net logger logs Exceptions as part of the Log message instead of a separate property like Serilog does.

**Comment by tsimbalar** [comment]
I've seen that also in cases where the "message template" contains new-lines ... 
But I guess it's by design, expanding multiple line would probably break the page layout.

Example below, the message template had multiple lines, and the same content is used in property `OriginalMsg` . The property one renders fine: 

![image](https://user-images.githubusercontent.com/160544/31598999-d2290284-b250-11e7-9e84-ddc41757c429.png)

*(please don't judge me based on the log messages 🐖  )*

**Comment by elv1s42** [comment]
Hi @nblumhardt !
As @andymac4182 mentioned, log4net logs exceptions as error messages , so there are no exception messages for it.

@tsimbalar , as far as I can see on the screenshot, line breaks are not working for you

**Comment by tsimbalar** [comment]
@elv1s42 they are working in the bottom part (where the property is named `OriginalMsg`), but not in the *RenderedMessage* (the part that starts after the red dot)

**Comment by elv1s42** [comment]
@tsimbalar, ok, I got it.

I was expecting it to work for Rendered message as well.
If it is not a bug, then I'll just keep my local fix (edited .css file) for RenderedMessage, and this issue can be closed.

**Comment by tsimbalar** [comment]
I think it's supposed to be that way, but I'm just a Seq user, not the owner :p check with @nblumhardt ;)

BTW, for your custom CSS tweaks, I would recommend to put them in your theme : 

![image](https://user-images.githubusercontent.com/160544/31616361-d0d5e870-b28c-11e7-9184-5c80c9d6ae3d.png)


rather than monkey-patching the css ;) ... this way you won't have issues with the product upgrades

**Comment by elv1s42** [comment]
@tsimbalar, thank you very much, I'll follow your advise.

@nblumhardt, if it is not a bug, then I'll just keep my fix for RenderedMessage, and this issue can be closed

**Comment by nblumhardt** [comment]
Ah, thanks @andymac4182 and @tsimbalar - it is something like that 👍 

Unfortunately, log4net's `ILogger` is a bit odd when it comes to recording exceptions.

If you use the `ILogger.Error()` overload like:

```csharp
log.Error("Oops!", ex);
```

You'll get what you expect:

![image](https://user-images.githubusercontent.com/342712/31637513-65124ea4-b312-11e7-830a-a43185670aa9.png)

You can't use `ErrorFormat()` in this way, though.

The solution is to use something like string interpolation and `Error()`:

```csharp
log.Error($"The {thing} broke", ex);
```

When the exception is passed through log4net as an `Exception` it'll end up in the log event's `ExceptionObject` property and go to Seq as an exception rather than part of the message:

https://github.com/datalust/seq-client/blob/master/src/Seq.Client.Log4Net/Client/Log4Net/LoggingEventFormatter.cs#L92

Hope this helps, let me know if anything's unclear :-) Thanks!

**Comment by elv1s42** [comment]
@nblumhardt, thank you for the update, I'll start using suggested approach of logging exceptions.
But at the moment I can't change all places in the code where we are logging exceptions.

So I'll use new way of logging exceptions as well as new theme for Seq: 
![image](https://user-images.githubusercontent.com/6689884/31655931-0338dc40-b333-11e7-845a-91142393e0f2.png)

But anyway I think that line breaks should work when we are logging an Error.

Thank you.

**Comment by nblumhardt** [comment]
Looks great, thanks @elv1s42.
